import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuwidget/generated/GeneratedMenudeRegistroWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuwidget/generated/GeneratedUnsplash16_gBi18T0Widget.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuwidget/generated/GeneratedImgTemBaseWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuwidget/generated/GeneratedBuscadorWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuwidget/generated/GeneratedMenuInferiorWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuwidget/generated/GeneratedTemperaturaMasRecienteWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuwidget/generated/GeneratedImgTemBaseWidget1.dart';

/* Frame Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 239, 235, 235),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedMenuInferiorWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 6.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 65.0,
                child: GeneratedMenudeRegistroWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 90.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedBuscadorWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 21.0,
                child: GeneratedTemperaturaMasRecienteWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 333.0,
                child: GeneratedUnsplash16_gBi18T0Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 150.0,
                child: GeneratedImgTemBaseWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 376.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 150.0,
                child: GeneratedImgTemBaseWidget1(),
              )
            ]),
      ),
    ));
  }
}
