import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedaadirregistrowidget/generated/GeneratedMenuInferiorWidget1.dart';

/* Frame Añadir Registro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAadirRegistroWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 640.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 239, 235, 235),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 570.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 70.0,
                  child: GeneratedMenuInferiorWidget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
