import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedReadersharpWidget5.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedHomeWidget5.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedRegistrosWidget6.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedSettingssharpWidget5.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedPersoncirclesharpWidget5.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedAddcircleWidget5.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedMenuWidget6.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedRectangle3Widget5.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedAjustesWidget6.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuinferiorwidget5/generated/GeneratedPerfilWidget6.dart';

/* Component Menu Inferior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuInferiorWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 70.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 70.0,
              child: GeneratedRectangle3Widget5(),
            ),
            Positioned(
              left: 26.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedHomeWidget5(),
            ),
            Positioned(
              left: 99.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedSettingssharpWidget5(),
            ),
            Positioned(
              left: 312.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedPersoncirclesharpWidget5(),
            ),
            Positioned(
              left: 239.0,
              top: 20.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 30.0,
              child: GeneratedReadersharpWidget5(),
            ),
            Positioned(
              left: 154.0,
              top: 6.0,
              right: null,
              bottom: null,
              width: 60.0,
              height: 60.0,
              child: GeneratedAddcircleWidget5(),
            ),
            Positioned(
              left: 27.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 34.0,
              height: 19.0,
              child: GeneratedMenuWidget6(),
            ),
            Positioned(
              left: 95.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 43.0,
              height: 19.0,
              child: GeneratedAjustesWidget6(),
            ),
            Positioned(
              left: 230.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 54.0,
              height: 19.0,
              child: GeneratedRegistrosWidget6(),
            ),
            Positioned(
              left: 313.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 32.0,
              height: 19.0,
              child: GeneratedPerfilWidget6(),
            )
          ]),
    ));
  }
}
