import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/appfigmaapp/generatedshieldcheckmarkwidget/generated/GeneratedVectorWidget63.dart';

/* Frame shield-checkmark
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedShieldcheckmarkWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 13.0,
        height: 13.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8749712430513822;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      11.374626159667969;

                  double percentHeight = 0.8750151120699369;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      11.37519645690918;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.06251443349398099,
                        translateY: constraints.maxHeight * 0.06249969280683077,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget63())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
