import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generateddropdownwidget/generated/GeneratedClosecircleWidget.dart';
import 'package:flutterapp/appfigmaapp/generateddropdownwidget/generated/GeneratedDocumentattachWidget.dart';
import 'package:flutterapp/appfigmaapp/generateddropdownwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/appfigmaapp/generateddropdownwidget/generated/GeneratedCambiarRegistroWidget.dart';
import 'package:flutterapp/appfigmaapp/generateddropdownwidget/generated/GeneratedEliminarRegistroWidget.dart';

/* Component Drop Down
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDropDownWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 132.0,
      height: 62.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 132.0,
              height: 62.0,
              child: GeneratedRectangle8Widget(),
            ),
            Positioned(
              left: 17.0,
              top: 38.0,
              right: null,
              bottom: null,
              width: 117.0,
              height: 15.0,
              child: GeneratedEliminarRegistroWidget(),
            ),
            Positioned(
              left: 17.0,
              top: 13.0,
              right: null,
              bottom: null,
              width: 117.0,
              height: 15.0,
              child: GeneratedCambiarRegistroWidget(),
            ),
            Positioned(
              left: 10.0,
              top: 37.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedClosecircleWidget(),
            ),
            Positioned(
              left: 10.0,
              top: 12.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedDocumentattachWidget(),
            )
          ]),
    ));
  }
}
