import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedregistrosusuariowidget3/generated/GeneratedMaskgroupWidget6.dart';
import 'package:flutterapp/appfigmaapp/generatedregistrosusuariowidget3/generated/GeneratedRestrousuarioWidget3.dart';
import 'package:flutterapp/appfigmaapp/generatedregistrosusuariowidget3/generated/GeneratedLine1Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/appfigmaapp/generatedregistrosusuariowidget3/generated/GeneratedEllipsisverticalWidget3.dart';

/* Component Registros Usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrosUsuarioWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 304.0,
      height: 58.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.2352941161707828;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedMaskgroupWidget6(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.5568627809223375;

                final double height =
                    constraints.maxHeight * 0.6333332719474003;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.2705882473995811,
                      y: constraints.maxHeight * 0.18333333114097858,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRestrousuarioWidget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.07843138042249177;

                final double height =
                    constraints.maxHeight * 0.3333333442951071;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.9215686195775082,
                      y: constraints.maxHeight * 0.3333333442951071,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedEllipsisverticalWidget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 1.000001405414782;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 304.00042724609375;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: 0,
                      translateY: constraints.maxHeight * 1.174999894766972,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: 1,
                      scaleZ: 1,
                      child: GeneratedLine1Widget3())
                ]);
              }),
            )
          ]),
    ));
  }
}
