import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedMenudeRegistroWidget1.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedDiegoRodriguezWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedRegistrosUsuarioWidget2.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedRegistrosUsuarioWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedBotonWidget2.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedRegistrosUsuarioWidget1.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedMenuInferiorWidget2.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedUsuarioVerificadoWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedperfilwidget2/generated/GeneratedBannerWidget.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 239, 235, 235),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedMenuInferiorWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedMenudeRegistroWidget1(),
              ),
              Positioned(
                left: 19.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 150.0,
                child: GeneratedBannerWidget(),
              ),
              Positioned(
                left: 136.0,
                top: 254.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 21.0,
                child: GeneratedDiegoRodriguezWidget(),
              ),
              Positioned(
                left: 152.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 17.0,
                child: GeneratedUsuarioVerificadoWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 58.0,
                child: GeneratedRegistrosUsuarioWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 58.0,
                child: GeneratedRegistrosUsuarioWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 446.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 58.0,
                child: GeneratedRegistrosUsuarioWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 49.0,
                child: GeneratedBotonWidget2(),
              )
            ]),
      ),
    ));
  }
}
