import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedajusteswidget4/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/appfigmaapp/generatedajusteswidget4/generated/GeneratedLoscambiosquerealicesseveranreflejadoinmediatamenteWidg.dart';
import 'package:flutterapp/appfigmaapp/generatedajusteswidget4/generated/GeneratedOpcionesWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedajusteswidget4/generated/GeneratedMenuInferiorWidget4.dart';
import 'package:flutterapp/appfigmaapp/generatedajusteswidget4/generated/GeneratedConfiguraTusPreferenciasWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedajusteswidget4/generated/GeneratedOpcionesWidget3.dart';
import 'package:flutterapp/appfigmaapp/generatedajusteswidget4/generated/GeneratedBotonWidget3.dart';
import 'package:flutterapp/appfigmaapp/generatedajusteswidget4/generated/GeneratedMenudeRegistroWidget3.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 239, 235, 235),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 70.0,
                child: GeneratedMenuInferiorWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 15.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 60.0,
                child: GeneratedMenudeRegistroWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 430.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 208.0,
                height: 21.0,
                child: GeneratedConfiguraTusPreferenciasWidget(),
              ),
              Positioned(
                left: 47.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 32.0,
                child:
                    GeneratedLoscambiosquerealicesseveranreflejadoinmediatamenteWidg(),
              ),
              Positioned(
                left: 41.0,
                top: 191.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 98.0,
                child: GeneratedOpcionesWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 278.0,
                height: 152.0,
                child: GeneratedOpcionesWidget3(),
              ),
              Positioned(
                left: 30.0,
                top: 466.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 49.0,
                child: GeneratedBotonWidget3(),
              )
            ]),
      ),
    ));
  }
}
