import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedinputwidget2/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/appfigmaapp/generatedinputwidget2/generated/GeneratedIngresatuEmailWidget1.dart';

/* Group Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 300.0,
      height: 50.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 300.0,
              height: 50.0,
              child: GeneratedRectangle2Widget3(),
            ),
            Positioned(
              left: 26.0,
              top: 16.0,
              right: null,
              bottom: null,
              width: 123.0,
              height: 21.0,
              child: GeneratedIngresatuEmailWidget1(),
            )
          ]),
    ));
  }
}
