import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedtoggleonwidget/generated/GeneratedToggleonWidget1.dart';

/* Frame Toggle on
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedToggleonWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 60.0,
      height: 30.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 60.0,
              height: 30.0,
              child: GeneratedToggleonWidget1(),
            )
          ]),
    ));
  }
}
