import 'package:flutter/material.dart';

/* Rectangle Perfil 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfil1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 60.0,
      height: 68.20945739746094,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/491c7828a1c3e8f0416d4c277174f66120319dc2.png",
          color: null,
          fit: BoxFit.cover,
          width: 60.0,
          height: 68.20945739746094,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
