import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedHolaIngresatusDatosWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedEyeWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedAcuario_01Widget.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedBienvenidoWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/appfigmaapp/generatedloginwidget/generated/GeneratedRectangle2Widget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedAcuario_01Widget(),
              ),
              Positioned(
                left: 77.0,
                top: 200.0,
                right: null,
                bottom: null,
                width: 211.0,
                height: 54.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 206.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 47.0,
                child: GeneratedBienvenidoWidget(),
              ),
              Positioned(
                left: 40.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 292.0,
                height: 45.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 19.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 50.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 288.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 20.0,
                child: GeneratedEyeWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 21.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 49.0,
                child: GeneratedBotonWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 281.0,
                height: 47.0,
                child: GeneratedHolaIngresatusDatosWidget(),
              )
            ]),
      ),
    ));
  }
}
