import 'package:flutter/material.dart';
import 'package:flutterapp/appfigmaapp/generatedmenuderegistrowidget4/generated/GeneratedRegistrosdeTemperaturasWidget4.dart';

/* Component Menu de Registro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenudeRegistroWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 60.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 82.0,
                  top: 20.0,
                  right: null,
                  bottom: null,
                  width: 197.0,
                  height: 21.0,
                  child: GeneratedRegistrosdeTemperaturasWidget4(),
                )
              ]),
        ),
      ),
    ));
  }
}
